# Generated by Django 4.2.7 on 2023-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamYearID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("league", models.CharField(max_length=2)),
                ("team_id", models.CharField(max_length=3)),
                ("franchise_id", models.CharField(max_length=3)),
                ("fangraphs_team_id", models.IntegerField()),
                ("baseball_reference_team_id", models.CharField(max_length=3)),
                ("retrosheet_team_id", models.CharField(max_length=3)),
            ],
        ),
    ]
